## static_countries
UPDATE static_countries SET cn_short_tr='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_tr='Birleşik Arap Emirlikleri' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_tr='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_tr='Antigua ve Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_tr='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_tr='Arnavutluk' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_tr='Ermenistan' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_tr='Hollanda Antilleri' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_tr='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_tr='Antarktika' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_tr='Bangladeş' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_tr='Amerikan Samoası' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_tr='Avusturya' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_tr='Avustralya' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_tr='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_tr='Azerbaycan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_tr='Bosna Hersek' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_tr='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_tr='Bangladeş' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_tr='Belçika' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_tr='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_tr='Bulgaristan' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_tr='Bahreyn' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_tr='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_tr='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_tr='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_tr='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_tr='Bolivya' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_tr='Brezilya' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_tr='Bahamalar' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_tr='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_tr='Bouvet Adası' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_tr='Botsvana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_tr='Beyaz Rusya' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_tr='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_tr='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_tr='Cocos Adaları' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_tr='Demokratik Kongo Cumhuriyeti' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_tr='Orta Afrika Cumhuriyeti' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_tr='Kongo Cumhuriyeti' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_tr='İsviçre' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_tr='Fildişi Sahili' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_tr='Cook Adaları' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_tr='Şili' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_tr='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_tr='Çin (Halk Cumhuriyeti)' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_tr='Kolombiya' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_tr='Kosta Rika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_tr='Küba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_tr='Yeşil Burun Adaları' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_tr='Christmas Adası' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_tr='Kıbrıs Cumhuriyeti' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_tr='Çekya' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_tr='Almanya' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_tr='Cibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_tr='Danimarka' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_tr='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_tr='Dominik Cumhuriyeti' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_tr='Cezayir' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_tr='Ekvador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_tr='Estonya' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_tr='Mısır' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_tr='Batı Sahra' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_tr='Eritre' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_tr='İspanya' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_tr='Etyopya' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_tr='Finlandiya' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_tr='Fiji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_tr='Falkland Adaları' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_tr='Mikronezya' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_tr='Faroe Adaları' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_tr='Fransa' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_tr='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_tr='İngiltere' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_tr='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_tr='Gürcistan' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_tr='Fransız Guyanası' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_tr='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_tr='Cebelitarık' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_tr='Grönland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_tr='Gambiya' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_tr='Gine' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_tr='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_tr='Ekvator Ginesi' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_tr='Yunanistan' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_tr='Güney Georgia ve Güney Sandwich Adaları' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_tr='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_tr='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_tr='Gine-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_tr='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_tr='Hong Kong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_tr='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_tr='Hırvatistan' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_tr='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_tr='Macaristan' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_tr='Endonezya' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_tr='İrlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_tr='İsrail' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_tr='Hindistan' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_tr='Britanya Hint Okyanusu Toprakları' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_tr='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_tr='İran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_tr='İzlanda' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_tr='İtalya' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_tr='Jamaika' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_tr='Ürdün' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_tr='Japonya' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_tr='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_tr='Kırgızistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_tr='Kamboçya' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_tr='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_tr='Komorlar' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_tr='Saint Kitts ve Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_tr='Kore Demokratik Halk Cumhuriyeti (Kuzey Kore)' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_tr='Güney Kore' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_tr='Kuveyt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_tr='Cayman Adaları' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_tr='Kazakistan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_tr='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_tr='Lübnan' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_tr='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_tr='Lihtenştayn' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_tr='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_tr='Liberya' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_tr='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_tr='Litvanya' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_tr='Lüksemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_tr='Letonya' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_tr='Libya' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_tr='Fas' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_tr='Monako' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_tr='Moldova' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_tr='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_tr='Marshall Adaları' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_tr='Makedonya' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_tr='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_tr='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_tr='Moğolistan' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_tr='Makao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_tr='Kuzey Mariana Adaları' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_tr='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_tr='Moritanya' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_tr='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_tr='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_tr='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_tr='Maldivler' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_tr='Malavi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_tr='Meksika' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_tr='Malezya' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_tr='Mozambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_tr='Namibya' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_tr='Yeni Kaledonya' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_tr='Nijer' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_tr='Norfolk Adası' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_tr='Nijerya' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_tr='Nikaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_tr='Hollanda' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_tr='Norveç' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_tr='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_tr='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_tr='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_tr='Yeni Zelanda' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_tr='Umman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_tr='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_tr='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_tr='Fransız Polinezyası' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_tr='Papua Yeni Gine' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_tr='Filipinler' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_tr='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_tr='Polonya' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_tr='Saint Pierre ve Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_tr='Pitcairn Adaları' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_tr='Porto Riko' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_tr='Portekiz' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_tr='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_tr='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_tr='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_tr='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_tr='Romanya' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_tr='Rusya' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_tr='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_tr='Suudi Arabistan' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_tr='Solomon Adaları' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_tr='Seyşeller' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_tr='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_tr='İsveç' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_tr='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_tr='Saint Helena, Ascension ve Tristan da Cunha' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_tr='Slovenya' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_tr='Svalbard' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_tr='Slovakya' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_tr='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_tr='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_tr='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_tr='Somali' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_tr='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_tr='São Tomé e Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_tr='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_tr='Suriye' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_tr='Eswatini' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_tr='Turks ve Caicos Adaları' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_tr='Çad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_tr='Fransız Güney Toprakları' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_tr='Gitmek' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_tr='Tayland' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_tr='Tacikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_tr='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_tr='Türkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_tr='Tunus' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_tr='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_tr='Timor-Leste' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_tr='Türkiye' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_tr='Trinidad ve Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_tr='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_tr='Tayvan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_tr='Tanzanya' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_tr='Ukrayna' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_tr='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_tr='Amerika Birleşik Devletleri\'nin küçük dış adaları' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_tr='Amerika Birleşik Devletleri (ABD)' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_tr='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_tr='Özbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_tr='Vatikan Şehri' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_tr='Saint Vincent ve Grenadinler' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_tr='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_tr='İngiliz Virgin Adaları' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_tr='Amerika Birleşik Devletleri Virgin Adaları' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_tr='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_tr='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_tr='Wallis ve Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_tr='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_tr='Yemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_tr='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_tr='Güney Afrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_tr='Zambiya' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_tr='Zimbabve' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_tr='Filistin' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_tr='Sırbistan ve Karadağ' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_tr='Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_tr='Heard ve McDonald Adaları' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_tr='Karadağ' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_tr='Sırbistan' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_tr='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_tr='bir tür inek' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_tr='Man Adası' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_tr='Aziz Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_tr='Saint Barthelemy' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_tr='Bonaire, Sint Eustatius ve Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_tr='Curacao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_tr='Sint Maarten' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_tr='Güney Sudan' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_tr='Kosova' WHERE cn_iso_2='XK';